// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdwWCMCOZ-9Qx7j7COYojGHN7lvo4179k',
    appId: '1:402656408782:web:eb7695c25d90b7974e4c9f',
    messagingSenderId: '402656408782',
    projectId: 'notesez',
    authDomain: 'notesez.firebaseapp.com',
    storageBucket: 'notesez.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfgVPZfOT2nBfbrKAOfQPHb3cuOHBbQpA',
    appId: '1:402656408782:android:61eb6e3221f09ea44e4c9f',
    messagingSenderId: '402656408782',
    projectId: 'notesez',
    storageBucket: 'notesez.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbC2QFgxXweT9WgBBjNHIGsvXVFrCr17s',
    appId: '1:402656408782:ios:f43b5cebd43137704e4c9f',
    messagingSenderId: '402656408782',
    projectId: 'notesez',
    storageBucket: 'notesez.appspot.com',
    iosClientId: '402656408782-nota01ljsk9q49c8jkugk2g400ft1an5.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbC2QFgxXweT9WgBBjNHIGsvXVFrCr17s',
    appId: '1:402656408782:ios:f43b5cebd43137704e4c9f',
    messagingSenderId: '402656408782',
    projectId: 'notesez',
    storageBucket: 'notesez.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdwWCMCOZ-9Qx7j7COYojGHN7lvo4179k',
    appId: '1:402656408782:web:d9a475c59fc83eba4e4c9f',
    messagingSenderId: '402656408782',
    projectId: 'notesez',
    authDomain: 'notesez.firebaseapp.com',
    storageBucket: 'notesez.appspot.com',
  );
}